import React from "react";

const QuestionAnswer = () => {
  return (
    <div className="p-4 bg-gray-100 rounded-xl mb-10" id="questionAnswer">
      <div
        tabIndex={0}
        className="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box"
      >
        <div className="collapse-title text-xl font-medium">Props vs state</div>
        <div className="collapse-content">
        <ul>
            <li>Props are generated by parent, data in props are consumed by the child</li>
            <li>state is declared and used locally, unlike props cannot directly used remotely(without the help of props)</li>
            <li>state can be updated, and update data is instantly useable.</li>
            <li>static props cannot be update unless send by a state</li>
        </ul>
        </div>
      </div>
      <div
        tabIndex={0}
        className="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box"
      >
        <div className="collapse-title text-xl font-medium">
          How does useState work?
        </div>
        <div className="collapse-content">
          <p>useState return an array</p>
          <p>within that array 2 items are send: variable & callback function</p>
          <p>callback function is use to update the stored data</p>
          <p>whereas the variable is responsible for showing the data</p>
          <p>useState can also take a default value</p>
        </div>
      </div>
      <div
        tabIndex={0}
        className="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box"
      >
        <div className="collapse-title text-xl font-medium">
          Purpose of useEffect other than fetching data
        </div>
        <div className="collapse-content">
          <p>any asynchronous es6 function like settimeout vs setinterval are required to used inside useEffect</p>
          <p>if any thing depends on other function to complete first is also can be written within it with the help of dependency</p>
          <p>onChange of firebase is set to state by useEffect</p>
          <p>Running on state change trigger animation on new array value</p>
        </div>
      </div>
      <div
        tabIndex={0}
        className="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box"
      >
        <div className="collapse-title text-xl font-medium">
          How Does React work?
        </div>
        <div className="collapse-content">
          <p>react is useful for SPA sites where only one page will do all the things with the help of react-router-dom</p>
          <p>react produces a virtual DOM to render html like code(JSX)</p>
          <p>However, behind the scene react converts the JSX code into real JS code with the help of babel</p>
          <p>previously react uses class based components</p>
          <p>however, functional components are getting very popular because hooks</p>
        </div>
      </div>
    </div>
  );
};

export default QuestionAnswer;
